### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by gielk** [markusressel/barcode-server#162] opened 2023-04-26 18:24 UTC
**Describe the bug**
I get an _Illegal instruction_ and then the server closes.

**Expected behavior**
Pushing to MQTT server. I have a Mosquitto broker running in Home Assistant and want to get the scanned barcode there to trigger an event.

**Screenshots**

```
gielk@barcodescanner:~ $ ./venv/bin/barcode-server run
2023-04-26 20:18:16,683 - barcode_server - INFO - === barcode-server ===
2023-04-26 20:18:16,685 - barcode_server - INFO - Instance ID: koelkast-scanner
2023-04-26 20:18:17,119 - barcode_server - INFO - Starting statistics webserver...
2023-04-26 20:18:17,168 - barcode_server.webserver - DEBUG - Starting notifier: mqtt
2023-04-26 20:18:17,170 - barcode_server.webserver - INFO - Starting webserver on 127.0.0.1:9654 ...
2023-04-26 20:18:17,216 - barcode_server.barcode - INFO - Reading: /dev/input/event1: Name: Metrologic Metrologic Scanner, Vendor: 0c2e, Product: 0200
2023-04-26 20:18:21,538 - barcode_server.barcode - INFO - Metrologic Metrologic Scanner (/dev/input/event1): 4056489340591
Illegal instruction
```

This is the config.

```
barcode_server:

  # (optional) the verbosity level of log output
  log_level: DEBUG

  # (optional) an identifier for this barcode-server instance
  # if omitted, this will be a UUIDv4
  id: koelkast-scanner

  # (optional) MQTT push configuration
  mqtt:
    # MQTT server host address
    host: "192.168.178.84"
    # (optional) MQTT server port
    port: 1883
    # (optional) Client ID of this barcode-server instance to provide to the MQTT server
    client_id: "barcode-server"
    # MQTT topic to push events to
    topic: "barcode-server/barcode"
    # Username to use when connecting to the MQTT server
    user: "mqtt"
    # Password to use when connecting to the MQTT server
    password: "_********_"
    # (optional) QoS value of event messages
    qos: 2
    # (optional) Whether to instruct the MQTT server to remember event messages between restarts (of the MQTT server)
    retain: True

  # A list of regex patterns to match USB device names against
  devices:
    - ".*Barcode.*"
    - ".*Scanner.*"
  # A list of absolute file paths to devices
  device_paths:
  #- "/dev/input/barcode_scanner"
```

**Desktop (please complete the following information):**
Raspberry Pi zero w
Raspberry Pi os 32 bit

**Comment by gielk** [comment] 2023-04-26 18:26
Info about the scanner:

Eclipse Model MS5145

```
I: Bus=0003 Vendor=0c2e Product=0200 Version=0111
N: Name="Metrologic Metrologic Scanner"
P: Phys=usb-20980000.usb-1/input0
S: Sysfs=/devices/platform/soc/20980000.usb/usb1/1-1/1-1:1.0/0003:0C2E:0200.0006/input/input6
U: Uniq=
H: Handlers=sysrq kbd leds event1 
B: PROP=0
B: EV=120013
B: KEY=e080ffdf 1cfffff ffffffff fffffffe
B: MSC=10
B: LED=1f
```

**Comment by markusressel** [comment] 2023-04-26 20:51
"Illegal Instruction" means that the system architecture of your device is not able to able to run the instructions required by barcode-server. See: https://python-forum.io/thread-34489.html

In this case it's probably caused by the fact that barcode-server uses [orjson](https://github.com/ijl/orjson) to construct and parse JSON data, which only supports 64 bit systems.

**Comment by gielk** [comment] 2023-04-26 22:13
Oké I’m to noob for this 😅
So if I understand correctly I have to use an other OS? Or try to run it in docker? Or is it the barcode scanner?

**Comment by markusressel** [comment] 2023-04-27 17:20
You would have to run on a 64 bit system. ARM is supported, but only the 64 bit variant. I don't know if the pi zero has a 64 bit chip, but if it has one, you have to use a 64 bit os as well. If it's a 32 bit chip, the current implementation of barcode-server will not support it.

**Comment by gielk** [comment] 2023-04-28 08:49
Unfortunately, the Raspberry Pi Zero does not support 64-bit architectures, so you cannot run a 64-bit operating system on this device. However, I do have a Raspberry Pi 3 lying around that does support 64-bit, so I will try it on that device. Thanks for the information on the 64-bit support and the compatibility of the barcode-server. I will make sure to use the appropriate operating system and configuration for my Raspberry Pi 3.

**Comment by markusressel** [comment] 2023-05-18 00:48
I am closing this for now. Feel free to open a new issue if anything comes up.

**Closed by markusressel** 2023-05-18 00:48 UTC
Labels: question

**Comment by gielk** [comment] 2023-05-18 05:14
Sorry forgot to update. The problem is fixed! Thanks a lot for the support my project worked amazing.
